### PR TITLE
Hotfix/jpeg fix

### PR DESCRIPTION
**Pull request by zburgermeiszter**
I was unable to compile it on Ubuntu 14.04 because of some issues in a cpp source file of the jpeg module.
Not it works.

### CODE REVIEW

**Comment by kiran-geon** [comment]
Zoltan,

I tried installing mjpeg-streamer in my Ubuntu 14.04 laptop using npm without any of the  extra steps you mentioned. The toolchain is the default one which came from the standard ubuntu repos. The package got installed without any issues. Please see  the attached  log. If there is a specific reason for  adding the ppa repos, please let me know.
[test.txt](https://github.com/kiran-geon/node-mjpeg-streamer/files/74068/test.txt)

**Comment by zburgermeiszter** [comment]
Try testing it on a VPS or a virtualbox, because the v4l2camera package require gcc >= 4.9 and the default gcc is4.8 on Ubuntu 14.04.
What version of gcc do you have?

**Comment by kiran-geon** [comment]
gcc version is 4.8.2. I do not have a VPS to test this. I dont think it matter if  the Ubuntu installation is on VPS or  a laptop. 
I tried installing "v4l2camera@0.4.3" on my Ubuntu 14.04 laptop and this is the log:

```
kiran-Linux-Laptop:~$ sudo npm install v4l2camera@0.4.3
-
> v4l2camera@0.4.3 install ~/node_modules/v4l2camera
> node-gyp rebuild

make: Entering directory `~/node_modules/v4l2camera/build'
  CC(target) Release/obj.target/v4l2camera/capture.o
  CXX(target) Release/obj.target/v4l2camera/v4l2camera.o
  SOLINK_MODULE(target) Release/obj.target/v4l2camera.node
  SOLINK_MODULE(target) Release/obj.target/v4l2camera.node: Finished
  COPY Release/v4l2camera.node
make: Leaving directory `~/node_modules/v4l2camera/build'
v4l2camera@0.4.3 node_modules/v4l2camera
kiran-Linux-Laptop:~$ gcc -v 2>&1 | grep -w version
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
kiran-Linux-Laptop:~$ cat /etc/issue
Ubuntu 14.04 LTS \n \l

kiran-Linux-Laptop:~$
```

Sorry I still dont see the point of these extra steps.

**Comment by zburgermeiszter** [comment]
The v4lcamera v1.0.2 requires gcc 4.9, but my I had errors during compiling the "jpeg" module, but it seems working for you.

**Pull request closed without merging**
